#!/usr/bin/env python3
"""
Builds the animated splash icon from assets/logo-dark.svg.

The mark is four filled paths, which rules out the usual trimPathStart reveal --
that only animates a stroke. What suits filled letterforms is an assemble: each
piece fades up and settles from slightly small, in reading order, P then o then
u then cz.

The badge stays. A VectorDrawable can hold a gradient, so the whole thing is one
vector: a full-viewport rect carrying a radial gradient sampled from the icon
plate, with the mark drawn over it. That keeps the colour the flat-PNG version
had rather than trading it away for the animation.

Geometry matches the still version exactly. The splash canvas is 288dp and the
system masks it to a CIRCLE of the inner 192dp, so a square mark has to be sized
by its diagonal: 288 * (192/288) / sqrt(2) * 0.95 = 129 units, centred.
"""
import re, math, os

SVG = 'assets/logo-dark.svg'
OUT = 'android/app/src/main/res/drawable'
VIEW = 288.0
SRC = 454.0

# Sampled from assets/icon-background-dark.png: warm centre, near-black edge.
GRAD_INNER = '#FF621619'
GRAD_OUTER = '#FF140505'

DURATION = 300      # per piece
STAGGER = 70        # between pieces
START_SCALE = 0.90

paths = re.findall(r'\sd="([^"]*)"', open(SVG).read())
assert len(paths) == 4, f'expected 4 paths, found {len(paths)}'


def bbox(d):
    n = [float(x) for x in re.findall(r'-?\d+\.?\d*(?:e-?\d+)?', d)]
    xs, ys = n[0::2], n[1::2]
    return min(xs), min(ys), max(xs), max(ys)


# Reading order, identified from each path's box rather than export order or a
# sort. A sort by top edge gets this wrong: the cz path also carries the l and
# the connector, so it starts near the top of the mark despite reading last.
#
#   0: x 290-420, y 136-266   the u, upper right
#   1: x   0-433, y   0-380   the P, its bar and stem
#   2: x  61-189, y 136-268   the o, upper left
#   3: x   0-454, y  35-454   the l, the connector and the cz
ORDER = [1, 2, 0, 3]

def _verify(i, xr, yr):
    x0, y0, x1, y1 = bbox(paths[i])
    assert xr[0] <= x0 <= xr[1] and yr[0] <= y0 <= yr[1], (
        f'path {i} is not where this script expects; re-check the export before '
        f'trusting the assemble order')

_verify(1, (-1, 1), (-1, 1))        # P starts at the origin
_verify(2, (55, 70), (130, 145))    # o
_verify(0, (285, 300), (130, 145))  # u
_verify(3, (-1, 1), (30, 40))       # cz group
order = ORDER

side = VIEW * (192 / 288) / math.sqrt(2) * 0.95
scale = side / SRC
offset = (VIEW - side) / 2

groups = []
for slot, idx in enumerate(order):
    x0, y0, x1, y1 = bbox(paths[idx])
    px, py = (x0 + x1) / 2, (y0 + y1) / 2
    groups.append(f'''        <group
            android:name="g{slot}"
            android:pivotX="{px:.2f}"
            android:pivotY="{py:.2f}"
            android:scaleX="1"
            android:scaleY="1">
            <path
                android:name="p{slot}"
                android:fillColor="#FFFFFFFF"
                android:fillAlpha="1"
                android:pathData="{paths[idx]}" />
        </group>''')

vector = f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/build-splash-vector.py from {SVG}. Do not hand-edit. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="288dp"
    android:height="288dp"
    android:viewportWidth="{VIEW:.0f}"
    android:viewportHeight="{VIEW:.0f}">

    <!-- The badge. Bleeds to the viewport edge on purpose: the system mask
         crops it, and an inset would show an edge inside the circle. -->
    <path android:pathData="M0,0 L{VIEW:.0f},0 L{VIEW:.0f},{VIEW:.0f} L0,{VIEW:.0f} Z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="radial"
                android:centerX="{VIEW/2:.0f}"
                android:centerY="{VIEW/2:.0f}"
                android:gradientRadius="{VIEW*0.62:.0f}">
                <item android:offset="0.0" android:color="{GRAD_INNER}" />
                <item android:offset="1.0" android:color="{GRAD_OUTER}" />
            </gradient>
        </aapt:attr>
    </path>

    <!-- The mark, scaled from its own 454 box into the masked safe area. -->
    <group
        android:name="mark"
        android:translateX="{offset:.2f}"
        android:translateY="{offset:.2f}"
        android:scaleX="{scale:.5f}"
        android:scaleY="{scale:.5f}">
{chr(10).join(groups)}
    </group>
</vector>
'''

targets = []
for slot in range(4):
    begin = slot * STAGGER
    targets.append(f'''    <target android:name="p{slot}">
        <aapt:attr name="android:animation">
            <objectAnimator
                android:propertyName="fillAlpha"
                android:startOffset="{begin}"
                android:duration="{DURATION}"
                android:valueFrom="0"
                android:valueTo="1"
                android:valueType="floatType"
                android:interpolator="@android:interpolator/decelerate_quad" />
        </aapt:attr>
    </target>
    <target android:name="g{slot}">
        <aapt:attr name="android:animation">
            <set>
                <objectAnimator
                    android:propertyName="scaleX"
                    android:startOffset="{begin}"
                    android:duration="{DURATION}"
                    android:valueFrom="{START_SCALE}"
                    android:valueTo="1"
                    android:valueType="floatType"
                    android:interpolator="@android:interpolator/decelerate_quad" />
                <objectAnimator
                    android:propertyName="scaleY"
                    android:startOffset="{begin}"
                    android:duration="{DURATION}"
                    android:valueFrom="{START_SCALE}"
                    android:valueTo="1"
                    android:valueType="floatType"
                    android:interpolator="@android:interpolator/decelerate_quad" />
            </set>
        </aapt:attr>
    </target>''')

avd = f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/build-splash-vector.py. Do not hand-edit. -->
<animated-vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:drawable="@drawable/splash_icon_vector">

{chr(10).join(targets)}
</animated-vector>
'''

os.makedirs(OUT, exist_ok=True)
open(f'{OUT}/splash_icon_vector.xml', 'w').write(vector)
open(f'{OUT}/splash_icon_anim.xml', 'w').write(avd)
total = (len(order) - 1) * STAGGER + DURATION
print(f'mark {side:.0f} units of {VIEW:.0f} (scale {scale:.4f}, offset {offset:.1f})')
print(f'assemble order (reading order): {order}')
print(f'total animation {total}ms')
