export type WordType = 'verb' | 'noun' | 'adjective' | 'unknown'

export type PageId =
  | 'folder'
  | 'translate'
  | 'dynamic_feed'
  | 'question_mark'
  | 'spatial_audio'
  | 'add_page'
  | 'api_config'

export interface PageConfig {
  title: string
  icon: string
  desc: string
  gradient: string
}

// ─── Vocab entry sub-shapes ────────────────────────────────────────────────

export interface VerbConjugations {
  present: string[]
  past: string[]
  past2: string[]
}

export interface NounDeclensions {
  cases: string[]
  singular: string[]
  plural: string[]
}

// ─── Discriminated union for VocabEntry ────────────────────────────────────

interface VocabBase {
  id: string        // lemma — dedup key for localStorage
  enriched: boolean // false until enrich-card populates grammar tables
  pl: string
  en: string
  left: string
  right: string
  tags: WordType[]
  sourceContext?: {
    sentence: string
    translation: string
    addedFrom: 'sentence-mining' | 'manual' | 'import'
  }
}

export interface VocabVerb extends VocabBase {
  type: 'verb'
  conjugations: VerbConjugations | null
  otherForm: { label: string; word: string } | null
}

export interface VocabNoun extends VocabBase {
  type: 'noun'
  gender: string
  plAlt: string
  declensions: NounDeclensions | null
}

export interface AdjectiveDeclensions {
  cases: string[]
  masculine: string[]
  feminine: string[]
  neuter: string[]
  pluralMasc: string[]
  pluralNonMasc: string[]
}

export interface VocabAdjective extends VocabBase {
  type: 'adjective'
  declensions: AdjectiveDeclensions | null
}

export interface VocabUnknown extends VocabBase {
  type: 'unknown'
  info?: string
}

export type VocabEntry = VocabVerb | VocabNoun | VocabAdjective | VocabUnknown

// ─── Spaced-repetition review state (stored separately from VocabEntry) ───────

export interface ReviewState {
  interval: number          // days until next review
  easeFactor: number        // SM-2 ease factor, starts at 2.5
  dueDate: string           // ISO date 'YYYY-MM-DD'
  lastReviewed: string | null
  reviewCount: number
}

// ─── Sentence entries (generated by scripts/generate-sentences.js) ────────────

interface SentenceBase {
  id: string
  cardLemma: string
  targetForm: string
  polish: string
  english: string
  languageToolPassed: boolean
  approved: boolean
}

export interface SentenceNoun extends SentenceBase {
  cardType: 'noun'
  targetCase: string
  targetNumber: string
}

export interface SentenceVerb extends SentenceBase {
  cardType: 'verb'
  targetPronoun: string
  targetTense: string
}

export interface SentenceAdjective extends SentenceBase {
  cardType: 'adjective'
  targetGender: string
  targetCase: string
  targetNumber: string
}

export type SentenceEntry = SentenceNoun | SentenceVerb | SentenceAdjective
