export type WordType = 'verb' | 'noun' | 'adjective' | 'unknown'

// Display label for a word type. The stored type stays 'unknown', but it reads
// as "Other" in the UI. Accepts a string so callers with wider unions (e.g. the
// translate page's 'adverb') can use it too.
export function typeLabel(type: string): string {
  return type === 'unknown' ? 'Other' : type
}

export type PageId =
  | 'folder'
  | 'translate'
  | 'dynamic_feed'
  | 'question_mark'
  | 'spatial_audio'
  | 'add_page'
  | 'api_config'

export interface PageConfig {
  title: string
  icon: string
  desc: string
  gradient: string
  /** Light-theme counterpart. Falls back to `gradient` where absent. */
  gradientLight?: string
  /** Flashcard hard-mode counterpart (dynamic_feed only). Falls back to `gradient`. */
  gradientHard?: string
  /** Light-theme hard-mode counterpart. Falls back to `gradientHard`. */
  gradientHardLight?: string
}

// ─── Vocab entry sub-shapes ────────────────────────────────────────────────

export interface VerbConjugations {
  present: string[]
  past: string[]
  past2: string[]
}

export interface NounDeclensions {
  cases: string[]
  singular: string[]
  plural: string[]
}

// ─── Discriminated union for VocabEntry ────────────────────────────────────

interface VocabBase {
  id: string        // lemma — dedup key for localStorage
  enriched: boolean // false until enrich-card populates grammar tables
  audioReady?: boolean // true once the PL+EN TTS clips are cached in IndexedDB
  /**
   * Came from the bundled starter deck rather than from the user. Marks which
   * cards a "remove the starter words" action may delete, so a new user can
   * clear the samples without hunting for them among their own words.
   */
  starter?: boolean
  pl: string
  en: string                  // primary translation (set at card creation)
  definitions?: string[]      // secondary English senses, filled during enrichment
  left: string
  right: string
  tags: WordType[]
  sourceContext?: {
    sentence: string
    translation: string
    addedFrom: 'sentence-mining' | 'manual' | 'import'
  }
}

export interface VocabVerb extends VocabBase {
  type: 'verb'
  conjugations: VerbConjugations | null
  otherForm: { label: string; word: string } | null
}

export interface VocabNoun extends VocabBase {
  type: 'noun'
  gender: string
  plAlt: string
  declensions: NounDeclensions | null
}

export interface AdjectiveDeclensions {
  cases: string[]
  masculine: string[]
  feminine: string[]
  neuter: string[]
  pluralMasc: string[]
  pluralNonMasc: string[]
}

export interface VocabAdjective extends VocabBase {
  type: 'adjective'
  declensions: AdjectiveDeclensions | null
  // Degrees of comparison (stopień wyższy / najwyższy), masc. nom. sg. Filled
  // during enrichment; empty string when the adjective isn't gradable, and
  // absent on cards enriched before this field existed.
  comparative?: string
  superlative?: string
}

export interface VocabUnknown extends VocabBase {
  type: 'unknown'
  info?: string
}

export type VocabEntry = VocabVerb | VocabNoun | VocabAdjective | VocabUnknown

// ─── Spaced-repetition review state (stored separately from VocabEntry) ───────

export interface ReviewState {
  interval: number          // days until next review
  easeFactor: number        // SM-2 ease factor, starts at 2.5
  dueDate: string           // ISO date 'YYYY-MM-DD'
  lastReviewed: string | null
  reviewCount: number
  // Progress toward "conquerable" in the flashcard game. Each left-swipe adds
  // 1 (normal mode) or 1.5 (hard mode); a right-swipe resets it. At >= 3 the
  // swipe-up-hold conquer gesture unlocks (3 normal / 2 hard left-swipes).
  conquerProgress?: number
  // True only when the card was explicitly conquered (swipe-up-hold / button) —
  // NOT inferred from the SRS interval, which grows past 180 on its own.
  conquered?: boolean
  // Strength score driving the flashcard "strong" grade: +1 per right-swipe;
  // a left-swipe resets it to 0 (or −1 if already negative); "Again" drops it to
  // −3. Floored at −3. Reflects getting the word right recently, not time in
  // rotation.
  strengthScore?: number
}

// ─── Quiz question records ───────────────────────────────────────────────────
//
// Historically these were only sentences generated by
// scripts/generate-sentences.js. They are now the record for a quiz question
// from any tier (see docs/tiered-quiz-generation-plan.md), which is why the
// sentence itself is optional: a `paradigm` question has no sentence at all,
// only a grammatical slot and the form that fills it.

/** Which tier produced this question. Absent on records written before tiers. */
export type QuestionSource = 'corpus' | 'generated' | 'paradigm'

interface SentenceBase {
  id: string
  cardLemma: string
  targetForm: string
  /** Absent for `paradigm` questions, which ask for the form with no context. */
  polish?: string
  english?: string
  languageToolPassed: boolean
  approved: boolean
  /** Undefined on pre-tier data, which all came from the desktop script. */
  source?: QuestionSource
  /** Corpus records only: the Tatoeba sentence id, so it can be traced back. */
  sourceRef?: string
}

export interface SentenceNoun extends SentenceBase {
  cardType: 'noun'
  targetCase: string
  targetNumber: string
}

export interface SentenceVerb extends SentenceBase {
  cardType: 'verb'
  targetPronoun: string
  targetTense: string
}

export interface SentenceAdjective extends SentenceBase {
  cardType: 'adjective'
  targetGender: string
  targetCase: string
  targetNumber: string
}

export type SentenceEntry = SentenceNoun | SentenceVerb | SentenceAdjective
